name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      - name: Generate tests
        run: cargo new --bin tests
        working-directory: ${{ github.workspace }}

      - name: Check for clippy warnings
        run: cargo clippy -- -D warnings
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: |
          cd tests
          cargo test
        working-directory: ${{ github.workspace }}

      - name: Audit dependencies
        run: cargo audit
        working-directory: ${{ github.workspace }}

      - name: Build release
        run: cargo build --release
        working-directory: ${{ github.workspace }}
