name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add a step to audit dependencies
      - name: Audit dependencies
        run: cargo audit
        working-directory: ${{ github.workspace }}

      # Add a step to build the release version
      - name: Build release
        run: cargo build --release
        working-directory: ${{ github.workspace }}
