name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add a step to set file permissions for the working directory (if needed)
      - name: Set file permissions
        run: chmod -R 755 .
        working-directory: ${{ github.workspace }}

      # Add a step to check if Cargo can parse the manifest
      - name: Check Cargo manifest
        run: cargo check --locked
        working-directory: ${{ github.workspace }}

      # Add other steps for testing, clippy checks, etc.
      - name: Check for clippy warnings
        run: cargo clippy -- -D warnings
        working-directory: ${{ github.workspace }}

      - name: Run tests
        run: cargo test
        working-directory: ${{ github.workspace }}

      - name: Audit dependencies
        run: cargo audit
        working-directory: ${{ github.workspace }}

      - name: Build release
        run: cargo build --release
        working-directory: ${{ github.workspace }}
