name: Rust CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add a step to create tests
      - name: Create tests
        run: cargo test --lib
        working-directory: ${{ github.workspace }}

      # Add a step to check if Cargo can parse the manifest
      - name: Check Cargo manifest
        run: cargo check
        working-directory: ${{ github.workspace }}

      # Add a step to perform clippy checks
      - name: Check for clippy warnings
        run: cargo clippy -- -D warnings
        working-directory: ${{ github.workspace }}

      # Add a step to run tests
      - name: Run tests
        run: cargo test
        working-directory: ${{ github.workspace }}

      # Add a step to audit dependencies
      - name: Audit dependencies
        run: cargo audit
        working-directory: ${{ github.workspace }}

      # Add a step to build the release version
      - name: Build release
        run: cargo build --release
        working-directory: ${{ github.workspace }}
